extends Node
class_name HtmlUtil

static func write_html_header(html_file_ref: FileAccess) -> void:
    if not html_file_ref:
        return
    
    var start_time := Time.get_datetime_string_from_system()
    
    html_file_ref.store_line("<!DOCTYPE html>")
    html_file_ref.store_line("<html>")
    html_file_ref.store_line("<head>")
    html_file_ref.store_line("    <meta charset='UTF-8'>")
    html_file_ref.store_line("    <title>Game Log</title>")
    html_file_ref.store_line("")
    html_file_ref.store_line("    <style>")
    html_file_ref.store_line("        * { margin: 0; padding: 0; box-sizing: border-box; }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        body {")
    html_file_ref.store_line("            font-family: monospace;")
    html_file_ref.store_line("            font-size: 14px;")
    html_file_ref.store_line("            line-height: 1.5;")
    html_file_ref.store_line("            background-color: #0d1117;")
    html_file_ref.store_line("            color: #c9d1d9;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        /* LAYOUT */")
    html_file_ref.store_line("        .layout {")
    html_file_ref.store_line("            display: flex;")
    html_file_ref.store_line("            align-items: flex-start;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        .sidebar {")
    html_file_ref.store_line("            order: 2;")
    html_file_ref.store_line("            width: 300px;")
    html_file_ref.store_line("            padding: 20px;")
    html_file_ref.store_line("            border-left: 1px solid #30363d;")
    html_file_ref.store_line("")
    html_file_ref.store_line("            position: sticky;")
    html_file_ref.store_line("            top: 0;")
    html_file_ref.store_line("")
    html_file_ref.store_line("            align-self: flex-start; /* IMPORTANT fix for flex + sticky */")
    html_file_ref.store_line("")
    html_file_ref.store_line("            height: 100vh;")
    html_file_ref.store_line("            overflow-y: auto;")
    html_file_ref.store_line("")
    html_file_ref.store_line("            background-color: #0d1117;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        .main {")
    html_file_ref.store_line("            order: 1;   /* move to left */")
    html_file_ref.store_line("            flex: 1;")
    html_file_ref.store_line("            padding: 20px;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        .hidden {")
    html_file_ref.store_line("            display: none;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        /* TOGGLE BUTTON */")
    html_file_ref.store_line("        .toggle-btn {")
    html_file_ref.store_line("            position: fixed;")
    html_file_ref.store_line("            top: 10px;")
    html_file_ref.store_line("            right: 10px;")
    html_file_ref.store_line("            background: #161b22;")
    html_file_ref.store_line("            color: #c9d1d9;")
    html_file_ref.store_line("            border: 1px solid #30363d;")
    html_file_ref.store_line("            padding: 6px 10px;")
    html_file_ref.store_line("            cursor: pointer;")
    html_file_ref.store_line("            border-radius: 4px;")
    html_file_ref.store_line("            z-index: 1000;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        /* EXISTING STYLES */")
    html_file_ref.store_line("        .log-header {")
    html_file_ref.store_line("            color: #58a6ff;")
    html_file_ref.store_line("            border-bottom: 1px solid #30363d;")
    html_file_ref.store_line("            padding-bottom: 10px;")
    html_file_ref.store_line("            margin-bottom: 20px;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        .filter-container {")
    html_file_ref.store_line("            margin: 15px 0;")
    html_file_ref.store_line("            padding: 10px;")
    html_file_ref.store_line("            background-color: #161b22;")
    html_file_ref.store_line("            border-radius: 6px;")
    html_file_ref.store_line("            display: flex;")
    html_file_ref.store_line("            gap: 10px;")
    html_file_ref.store_line("            align-items: center;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        .filter-input {")
    html_file_ref.store_line("            flex: 1 1 auto;")
    html_file_ref.store_line("            min-width: 0; /* IMPORTANT: allows proper shrinking */")
    html_file_ref.store_line("            padding: 8px 12px;")
    html_file_ref.store_line("            background-color: #0d1117;")
    html_file_ref.store_line("            border: 1px solid #30363d;")
    html_file_ref.store_line("            border-radius: 4px;")
    html_file_ref.store_line("            color: #c9d1d9;")
    html_file_ref.store_line("            font-family: inherit;")
    html_file_ref.store_line("            font-size: 14px;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        .filter-input:focus {")
    html_file_ref.store_line("            outline: none;")
    html_file_ref.store_line("            border-color: #58a6ff;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        .filter-stats {")
    html_file_ref.store_line("            color: #8b949e;")
    html_file_ref.store_line("            font-size: 13px;")
    html_file_ref.store_line("            white-space: nowrap;")
    html_file_ref.store_line("            flex: 0 0 180px; /* fixed width */")
    html_file_ref.store_line("            text-align: right;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        .log-container {")
    html_file_ref.store_line("            margin-top: 10px;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        p {")
    html_file_ref.store_line("            margin: 2px 0;")
    html_file_ref.store_line("            white-space: pre-wrap;")
    html_file_ref.store_line("            padding: 2px 5px;")
    html_file_ref.store_line("            border-radius: 3px;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        p:hover {")
    html_file_ref.store_line("            background-color: #161b22;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        /* ASCII CAT */")
    html_file_ref.store_line("        .ascii-cat {")
    html_file_ref.store_line("            white-space: pre;")
    html_file_ref.store_line("            font-size: 12px;")
    html_file_ref.store_line("            color: #8b949e;")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("    </style>")
    html_file_ref.store_line("")
    html_file_ref.store_line("    <script>")
    html_file_ref.store_line("        function filterLogs() {")
    html_file_ref.store_line("            const filterText = document.getElementById('filterInput').value.toLowerCase();")
    html_file_ref.store_line("            const logEntries = document.querySelectorAll('#logContainer p');")
    html_file_ref.store_line("            let visibleCount = 0;")
    html_file_ref.store_line("")
    html_file_ref.store_line("            logEntries.forEach(entry => {")
    html_file_ref.store_line("                const text = entry.textContent.toLowerCase();")
    html_file_ref.store_line("                if (filterText === '' || text.includes(filterText)) {")
    html_file_ref.store_line("                    entry.style.display = '';")
    html_file_ref.store_line("                    visibleCount++;")
    html_file_ref.store_line("                } else {")
    html_file_ref.store_line("                    entry.style.display = 'none';")
    html_file_ref.store_line("                }")
    html_file_ref.store_line("            });")
    html_file_ref.store_line("")
    html_file_ref.store_line("            const stats = document.getElementById('filterStats');")
    html_file_ref.store_line("            if (filterText === '') {")
    html_file_ref.store_line("                stats.textContent = `Showing all ${logEntries.length} entries`;")
    html_file_ref.store_line("            } else {")
    html_file_ref.store_line("                stats.textContent = `Showing ${visibleCount} of ${logEntries.length} entries`;")
    html_file_ref.store_line("            }")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        function toggleCat() {")
    html_file_ref.store_line("            const sidebar = document.getElementById('catSidebar');")
    html_file_ref.store_line("            sidebar.classList.toggle('hidden');")
    html_file_ref.store_line("        }")
    html_file_ref.store_line("")
    html_file_ref.store_line("        document.addEventListener('DOMContentLoaded', function() {")
    html_file_ref.store_line("            const filterInput = document.getElementById('filterInput');")
    html_file_ref.store_line("")
    html_file_ref.store_line("            if (filterInput) {")
    html_file_ref.store_line("                filterInput.addEventListener('input', filterLogs);")
    html_file_ref.store_line("                filterInput.addEventListener('keypress', function(e) {")
    html_file_ref.store_line("                    if (e.key === 'Enter') {")
    html_file_ref.store_line("                        filterLogs();")
    html_file_ref.store_line("                    }")
    html_file_ref.store_line("                });")
    html_file_ref.store_line("            }")
    html_file_ref.store_line("")
    html_file_ref.store_line("            filterLogs();")
    html_file_ref.store_line("        });")
    html_file_ref.store_line("    </script>")
    html_file_ref.store_line("</head>")
    html_file_ref.store_line("")
    html_file_ref.store_line("<body>")
    html_file_ref.store_line("")
    html_file_ref.store_line("<button class=\"toggle-btn\" onclick=\"toggleCat()\">Toggle Cat</button>")
    html_file_ref.store_line("")
    html_file_ref.store_line("<div class=\"layout\">")
    html_file_ref.store_line("")
    html_file_ref.store_line("    <div id=\"catSidebar\" class=\"sidebar hidden\">")
    html_file_ref.store_line("        <div class=\"ascii-cat\">")
    html_file_ref.store_line(" /\\_/\\  ")
    html_file_ref.store_line("( o.o ) ")
    html_file_ref.store_line(" > ^ <  ")
    html_file_ref.store_line("")
    html_file_ref.store_line("  /\\_/\\  ")
    html_file_ref.store_line(" ( -.- ) ")
    html_file_ref.store_line("  > ^ <  ")
    html_file_ref.store_line("")
    html_file_ref.store_line("debug cat watching logs...")
    html_file_ref.store_line("        </div>")
    html_file_ref.store_line("    </div>")
    html_file_ref.store_line("")
    html_file_ref.store_line("    <div class=\"main\">")
    html_file_ref.store_line("        <div class='log-header'>")
    html_file_ref.store_line("            <h2>Game Log - %s</h2>" % start_time)
    html_file_ref.store_line("            <small>Session started</small>")
    html_file_ref.store_line("        </div>")
    html_file_ref.store_line("")
    html_file_ref.store_line("        <div class='filter-container'>")
    html_file_ref.store_line("            <input type='text' id='filterInput' class='filter-input' placeholder='Filter logs...'>")
    html_file_ref.store_line("            <span id='filterStats' class='filter-stats'>Loading entries...</span>")
    html_file_ref.store_line("        </div>")
    html_file_ref.store_line("")
    html_file_ref.store_line("        <div id='logContainer' class='log-container'>")
    html_file_ref.flush()
